<?php
/**
 * Implements hook_field_formatter_info().
 */
function simple_link_image_formatter_field_formatter_info() {
  return array(
    'simple_link_image_formatter_image_formatter' => array(
      'label' => t('Simple image formatted from a link'),
      'field types' => array('link_field'),
      'settings'  => array(
        'pic_width' => '512',
        'pic_ratio' => '_4_3'
      ),
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function simple_link_image_formatter_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  //This gets the view_mode where our settings are stored
  $display = $instance['display'][$view_mode];
  //This gets the actual settings
  $settings = $display['settings'];
  //Initialize the element variable
  $element = array();
  //Add your select box
  $element['pic_width'] = array(
    '#type'           => 'textfield',
    '#title'          => t('Image Width'),
    '#description'    => t('Enter the width of image'),
    '#default_value'  => $settings['pic_width'],
  );
  $element['pic_ratio'] = array(
    '#type'           => 'select',
    '#title'          => t('Image Ratio'),
    '#description'    => t('Select what ratio of image'),
    '#default_value'  => $settings['pic_ratio'],
    '#options'        => array(
      '_4_3' => '4/3',
      '_16_9'  => '16/9',
      '_1_1' => '1/1'
    ),
  );
  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function simple_link_image_formatter_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $summary = t('Use a @size width texture as an image with a @ratio ratio"', array(
    '@size' => $settings['pic_width'],
    '@ratio' => $settings['pic_ratio']
  ));
  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function simple_link_image_formatter_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  switch ($display['type']) {
    // This formatter simply outputs the user name as text.
    case 'simple_link_image_formatter_image_formatter':
			return simple_link_image_formatter_format($items, $display['settings']);
			break;
  }
}

function simple_link_image_formatter_format($items, $settings) {
	$element = array();
	$height = $settings['pic_width'];
	switch ($settings['pic_ratio']) {
	  case '_4_3':
	    $height = ($settings['pic_width'] / 4)*3;
	    break;
	  case '_16_9':
	    $height = ($settings['pic_width'] / 16)*9;
	    break;
	}
	$size = 'width="'. $settings['pic_width']. 'px" height="'. $height. 'px"';
	
	foreach ($items as $delta => $item) {
		$element[$delta] = array(
			'#type' => 'html_tag',
			'#tag' => 'div',
			'#value' => '<img '. $size. ' src="'. $item['url']. '" title="'.$item['title'].'" />',
		);
	}
	return $element;
}
